### ISSUE TITLE
Error in matvec

### ISSUE THREAD

**Issue by GlenHertz** [daanhb/Julia-tutorial#1]
Great tutorial.  I think you have an error in your matvec example:

``` Julia
function matvec(A, x)
    B = zeros(size(A,1))
    for j = 1:size(A,1)
        for i = 1:size(A,2)
            B[i] = B[i] + A[i,j]*x[j]
        end
    end
    B
end
```

I think the `size` dimensions are backwards.  Shouldn't it be:

``` Julia
function matvec(A, x)
    B = zeros(size(A,1))
    for j = 1:size(A,2)  # fix
        for i = 1:size(A,1) # fix
            B[i] = B[i] + A[i,j]*x[j]
        end
    end
    B
end
```

Since the first dimension is `i` and the second dimension is `j`.

**Comment by daanhb** [comment]
Oops! You're absolutely right. I remember switching the indices at the last minute to respect column-major ordering in memory. Fixed with latest commit, thanks for reporting!
